### ISSUE TITLE
Heat Map color bar and SHAP summary Plot

### ISSUE THREAD

**Issue by thoo** [behavioral-ds/VocationMap#1]
Hi,
Thanks for this nice article and also sharing the codes. Could you also share the heat map plot (Fig.3B) with the color bar since there is no color bar in the paper? Also it would be really great if you could also share  [SHAP](https://github.com/slundberg/shap) summary plot for xgboost.

**Comment by andrei-rizoiu** [comment]
Hi Thoo,

> Could you also share the heat map plot (Fig.3B) with the color bar since there is no color bar in the paper?

We committed new code and data which allows rebuilding the heatmap (Fig.3B). I have not explored added a color bar, but the underlying data is included in the repository and I guess you can look directly at the values in the confusion matrix.

> Also it would be really great if you could also share SHAP summary plot for xgboost.

We have not explored the SHAP summary. Given that the models were trained using python, and plotting was done using R, it might be a bit tricky to output that plot. Putting this one on hold for now.

Cheers, MAR.

**Comment by thoo** [comment]
Thanks.
