### ISSUE TITLE
How does one read this map?

### ISSUE THREAD

**Issue by m-7761** [behavioral-ds/VocationMap#2]
Going by some posts of this map with legends the colors are meaningless and arbitrarily assigned to professions so that they appear significant (are they related to big 5 personality traits?) and what the hell are the 2 axes supposed to represent. Why has no one labeled them? -30 to 30 what? Come on!

**Comment by andrei-rizoiu** [comment]
The short answer is "read the manual", in this case the paper.

From the paper you will learn that the map is a t-sne generated dimensionality reduction tool). Googling t-SNE, one learns that the axes are synthetic -- that is, they are automatically built to maximize some properties.

tl;dr: the axis are not connected to specific concepts, they are built artificially for visualization purposes. 

From the paper, you will also learn that the colors are based on automatic clustering.
